version: '3'
services:
  postgres:
    image: postgres:alpine
    environment: &db_env
      POSTGRES_USER: tandarcl
      POSTGRES_PASSWORD: tandarcl
  web:
    build: .
    command: yarn run dev
    tty: true
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      <<: *db_env
      APP_PORT: 3000
      DATABASE_URL: postgres://tandarcl:tandarcl@postgres/tandarcl
      TOKEN_SECRET: "${TOKEN_SECRET}"
